github: radian-software
patreon: radiansoftware
ko_fi: radiansoftware
liberapay: radian-software
open_collective: radian-software
buy_me_a_coffee: radiansoftware
custom:
  - https://www.paypal.com/donate/?hosted_button_id=SYF48KFJ95FPA

  # Cash App is not currently supported because they have blocked
  # my ability to sign in and have refused to provide any customer
  # support whatsoever, including to process legally mandated CCPA
  # data privacy requests. A report has been submitted to the office
  # of the California Attorney General on this matter.

  # Venmo is not currently supported because it is impossible to
  # create a new business account when one has been created at any
  # point in the past, even if it has been deleted. I have reached out
  # to Venmo support and they have confirmed there is no supported way
  # to use Venmo going forward, and suggested I use PayPal instead.
